version: "3.5"

services:

  backend:
    build: ./service/.
    container_name: warehouse
    links:  # figure out what this is!!
    - redis
    ports:
      - 4000:3000
    environment:
      - PORT=3000
      - REDIS_URL=redis://cache
  
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  dummypython:
    build: ./dummy/.
    environment:
      - API_URL=http://warehouse:3000/warehouse/products
